version: '3.8'
services:
  selenium-firefox:
    image: seleniarm/standalone-firefox:4.16.1
    platform: linux/arm64
    shm_size: 2g
    environment:
      - SE_NODE_SESSION_TIMEOUT=120
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
