version: '3.8'

services:
  test-desktop:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    shm_size: '2gb'
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
