version: '3.8'
services:
  selenium:
    image: seleniarm/standalone-chromium:4.25.0-20241019
    platform: linux/arm64
    shm_size: 2g
    environment:
      - SE_NODE_SESSION_TIMEOUT=120
      - SE_NODE_MAX_SESSIONS=1
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 10s
      timeout: 5s
      retries: 5

  selenium-firefox:
    image: seleniarm/standalone-firefox:4.25.0-20241019
    platform: linux/arm64
    shm_size: 2g
    environment:
      - SE_NODE_SESSION_TIMEOUT=120
      - SE_NODE_MAX_SESSIONS=1
    ports:
      - "4445:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 10s
      timeout: 5s
      retries: 5
