name: Test Suite (Desktop + Mobile)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-local:
    name: Run Tests (Desktop + Mobile)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Desktop Tests
      run: npm run test:desktop
      continue-on-error: true
      
    - name: Run Mobile Tests
      run: npm run test:mobile
      continue-on-error: true
      
    - name: Generate Allure Report
      if: always()
      run: |
        npm run allure:generate || true
      
    - name: Upload Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        retention-days: 7
        
    - name: Upload Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
        retention-days: 7

